# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: tinder-skills
      POSTGRES_USER: tinder-skills
      POSTGRES_DB: tinder-skills
    ports:
      - 5432:5432


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
